# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: v2
name: oci-onm-common
description: Common resources for OCI Management Gateway/Management Agent deployment helm charts
type: application
version: 1.0.3
appVersion: "1.0.3"
