# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: Service
metadata:
  name: {{ include "mgmt-gateway.resourceNamePrefix" . }}-mgmt-gateway
  namespace: {{ include "mgmt-gateway.namespace" . }}
  labels:
    app: {{ include "mgmt-gateway.resourceNamePrefix" . }}-mgmt-gateway
spec:
  type: {{ .Values.mgmtgateway.service.type }}
  ports: 
    - port: {{ .Values.mgmtgateway.service.port }}
      targetPort: {{ .Values.mgmtgateway.service.port }}
      protocol: TCP
      NodePort: {{ .Values.mgmtgateway.service.port }}
  selector:
    app: {{ include "mgmt-gateway.resourceNamePrefix" . }}-mgmt-gateway
