apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvgateway
spec:
  accessModes: [ "ReadWriteOnce" ]
  capacity:
   storage: 2Gi
  hostPath:
   path: /opt/oracle
  persistentVolumeReclaimPolicy: Delete
  storageClassName:
  claimRef:
    namespace: oci-onm
    name: pvcgateway
