apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcgateway
  namespace : oci-onm
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
     storage: 2Gi
  storageClassName:
