# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.

global:
  # -- Kubernetes Namespace in which the resources to be created. Set oci-kubernetes-monitoring-common:createNamespace set to true, if the namespace doesn't exist.
  namespace: oci-onm
  # -- Prefix to be attached to resources created through this chart. Not all resources may have this prefix.
  resourceNamePrefix: oci-onm
oci-onm-common:
   enabled: false
mgmtagent:
   # Provide either installKeyFileContent or installKey as an install key. If both provided then installKeyFileContent will take higher precedence.

   # -- Provide the base64 encoded content of the Management Agent Install Key file (e.g. cat input.rsp | base64 -w 0)
   installKeyFileContent: bWFuYWdlbWVudEFnZW50SW5zdGFsbEtleSA9IE1pNHdMSFZ6TFdGemFHSjFjbTR0TVN4dlkybGtNUzUwWlc1aGJtTjVMbTlqTVM0dVlXRmhZV0ZoWVdFMU5XTnVNM2x0Tkc1MGVuTTBiV2t6TjJWMVpUVnVZbm8zYUdKNVpYVnllbkIyYkRVM2VtcDNlV1Z3Ym5KaE5EZGtNM0J4TEc5amFXUXhMbTFoYm1GblpXMWxiblJoWjJWdWRHbHVjM1JoYkd4clpYa3ViMk14TG1saFpDNWhiV0ZoWVdGaFlYcHpORFIwZVhsaGJHc3pibTkwYkhad00zZDFjbWMxZFdrM2NuTndkM3BvWkRaNU5ITjFZbkExTW1oNVlUVnVaemMzYjJFc1NYaHdaMGhNVTNCdFNsRnpRME53UWtRM01EUkxSR293WDBKR2VVcDNZM1ExYUVWWFYwaFBOdz09IApDcmVkZW50aWFsV2FsbGV0UGFzc3dvcmQgPQpkaXNhYmxlRmlwcyA9IHRydWUKR2F0ZXdheVNlcnZlckhvc3Q9aG9zdC0xMC0wLTIwLTU2Lmxic3ViYjUwYTI5M2I1Lm1hbmFnZW1lbnRnYXRldy5vcmFjbGV2Y24uY29tCkdhdGV3YXlTZXJ2ZXJQb3J0PTQ0ODAKQnVmZmVyaW5nRW5hYmxlZD10cnVlCgo=
   # -- Copy the downloaded Management Agent Install Key file under root helm directory as resources/input.rsp
   installKey: resources/input.rsp
   # Follow steps documented at https://github.com/oracle/docker-images/tree/main/OracleManagementAgent to build docker image.
   image:
      # -- Replace this value with actual docker image URL for Management Agent
      url: iad.ocir.io/paasomcqa/mgmtagent-container:1.0.4
      # -- Image secrets to use for pulling container image (base64 encoded content of ~/.docker/config.json file)
      secret: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJpYWQub2Npci5pbyI6IHsKICAgICAgICAgICAgICAgICAgICAgICAgImF1dGgiOiAiY0dGaGMyOXRZM0ZoTDA5eVlXTnNaVWxrWlc1MGFYUjVRMnh2ZFdSVFpYSjJhV05sTDNacGFtRjVMbkV1YTNWdFlYSkFiM0poWTJ4bExtTnZiVHA5UlV0TU16ZHdOSFJ5VG5sb2MxMUhXa1ZIUkE9PSIKICAgICAgICAgICAgICAgIH0KICAgICAgICB9Cn0K

# -- Kubernetes namespace to create and install this helm chart in
namespace: "{{ .Values.global.namespace }}"

# -- Name of the Kubernetes ServiceAccount
serviceAccount: "{{ .Values.global.resourceNamePrefix }}"

deployment:
   security:
      # Processes in the Container will run as user ID 1000, replace it with a different value if desired
      runAsUser: 1000
      # Processes in the Container will use group ID 2000, replace it with a different value if desired
      runAsGroup: 2000
      # Files created in the Container will use group ID 2000, replace it with a different value if desired
      fsGroup: 2000

   # Please provide the current epoch time in seconds (Eg: Executing the following command in a bash shell will provide the epoch time: "date +%s") to clean up the agent installation directory from previous deployment
   cleanupEpochTime:

   # Setting the daemonset deployment to true, will deploy the Management Agents as a daemonset in addition to deploying the Management Agent as a statefulset. This is done to to distribute the node metrics collection to agents running on the node
   daemonSetDeployment: false
   
   daemonSet:
      # Provide the host path if Agent is deployed as DaemonSet. Management Agent Pod should have read-write access to it.
      hostPath:

   # Provide the agent resources as per Kubernetes resource quantity
   resource:
      # Provide the minimum required resources
      request:
         # specify the cpu cores
         cpuCore: 200m
         # specify the memory
         memory: 500Mi
         # specify the storage capacity for StatefulSet's PVC
         storage: 2Gi
      # Provide the maximum limit for resources
      limit:
         # specify the cpu cores
         cpuCore: 500m
         # specify the memory
         memory: 1Gi
   
   # Provide the storage class for StatefulSet's PVC. If not provided then the Cluster's default storage class will be used.
   storageClass:
